title:              Redux
description:        An absurdly bare-bones Jekyll theme.

baseurl:            /jekyll-theme-redux

author:
  name:             Laurent Boileau
  url:              https://laurentboileau.ca

theme:              jekyll-theme-redux
permalink:          pretty
paginate:           5

navigation:
  - title: About
    url: /jekyll-theme-redux/about
