author: Appelpodott
  name: Blog
  url:  # the author's homepage url
    
    
theme:              jekyll-theme-redux
permalink:          pretty
paginate:           5

navigation:
  - title: Readme
url: /appelpodott.github.io/Readme
